CONDUCT.md
CONTRIBUTING.md

Add contribution guidelines

---

src/desdemona/utils.clj

This fixes some problems highlighted in #13, hopefully making it easier for @reaperhulk to merge that.

Kibit fixes

---

.travis.yml
project.clj

Run kibit in CI

---

.travis.yml
project.clj

Fixes #12, depends on #13.
Suggestions welcome for the env var name. `EASTWOOD=false` is kind of annoying for "every test except eastwood"

Run eastwood in CI

---

.editorconfig
CONTRIBUTING.md

Add EditorConfig

---

.editorconfig
.travis.yml
CONTRIBUTING.md

Gating EditorConfig

---

README.md
script/build.sh
script/connect_kafka.sh
script/connect_mysql.sh
script/submit_job.sh

This PR improves the UX of the scripts a bit, and adds a missing instruction to the README.

Clean up scripts and README

---

src/desdemona/catalogs/sample_catalog.clj
src/desdemona/jobs/sample_submit_job.clj
src/desdemona/tasks/kafka.clj
src/desdemona/tasks/sql.clj
test/desdemona/jobs/sample_job_test.clj

Improve coverage by removing more unused code, adding test assertion

---

README.md

Document 2GB VM memory requirement

---

.travis.yml

Add docker-compose to Travis

---

.gitignore
project.clj
resources/ui/index.html
src/desdemona/ui/core.cljs

This should solve #64 enough so that @smogg can get started.

Add figwheel and basic ClojureScript infrastructure

---

.gitignore
.travis.yml
project.clj
src/desdemona/ui/core.cljs
test/desdemona/ui/core_test.cljs
test/desdemona/ui/runner.cljs

This builds on #68. This is currently a WIP; it is only open so that Travis builds stuff for me on occasion.

Add ClojureScript testing infrastructure based on doo + karma

---

src/desdemona/jobs/sample_submit_job.clj
src/desdemona/lifecycles/metrics.clj
test/desdemona/metrics_test.clj

This should help knock our coverage up a few percentage points.

Add metrics coverage

---

resources/ui/css/main.css
resources/ui/sass/_bootstrap.scss
resources/ui/sass/_nav.scss
resources/ui/sass/_spacing.scss
resources/ui/sass/_variables.scss
resources/ui/sass/main.scss
src/desdemona/ui/dom.cljs
src/desdemona/ui/nav.cljs
test/desdemona/ui/nav_test.cljs

This adds top navigation markup/basic styling generating something that looks like this:

Navigation

---

.travis.yml
docker-compose.yml

This gives everything time to finish starting up.
Kafka waits for 10 seconds for Zookeeper to finish. Desdemona itself waits 20 seconds for Kafka. (The waiting starts at the same time, so Desdemona's wait has to include Kafka's.)

Delaying the start of Kafka and Desdemona

---

.travis.yml

Refs #16, which is not currently a problem. (I'm suggesting we let it gate until there's an obvious case where it's suggesting we do something dumb, which hasn't been the case recently.)

Make eastwood, kibit gating

---

src/desdemona/query.clj
test/desdemona/query_test.clj

Add conjunction to the query language

---

src/desdemona/query.clj
test/desdemona/query_test.clj

Add disjunction to the query language

---

src/desdemona/lifecycles/logging.clj
test/desdemona/cli_test.clj
test/desdemona/jobs/sample_job_test.clj
test/desdemona/lifecycles/logging_test.clj
test/desdemona/test_macros.clj

This should improve our last bit of missing test coverage.

Clean up sample-job-test, add tests for logging logic

---

project.clj

This does not touch onyx (because that will presumably be a serious change). I was unable to upgrade cljfmt or figwheel; see #112.

Upgrade some dependencies

---

.jenkins/docker-compose-test.sh

add a bash script we can run in jenkins to run docker-compose tests

---

resources/infix-query-grammar.ebnf
src/desdemona/query.clj
test/desdemona/query_test.clj

Multi-arity features for the infix query language
